### ISSUE TITLE
Hackatón certamen

### ISSUE THREAD

**Issue by JJ** [M42/granasatClient#2]
¿No os queréis apuntar?

**Comment by M42** [comment]
Me temo que este proyecto ya quedó inactivo. Aunque hubiera sido muy interesante presentarlo en su tiempo, ya no serviría para un hackatón.

Estuve trabajando con el proyecto GranaSAT hasta el primer lanzamiento, en octubre del año pasado. Después abandoné el proyecto. Nadie continuó este código y no creo que se continúe en un futuro.

Sé que otros miembros del equipo tenían intención de presentar el proyecto al certamen; pero no creo que cumpliera requisitos porque no era un proyecto que fueran a desarrollar ellos durante este año, el cliente era un proyecto que desarrollamos @agarciamontoro y yo y que estaba ya finalizado. Si lo presentaron, creo que deberían plantearse borrarlo. 

Quizá @agarciamontoro pueda corregirme. Pero no creo que haya intención de continuar este proyecto.

**Comment by M42** [comment]
Por otro lado, si es intención de algún miembro del equipo de **GranaSAT** presentar este código al certamen, sugiero forkearlo y aclarar que yo no participo con este proyecto. Ayudaría a resolver computation-hs/comp-models#20

**Comment by JJ** [comment]
No hay problema, Mario. Ya aclarado.

**Comment by agarciamontoro** [comment]
Es justo como dice @M42, este proyecto está terminado y su participación en el CUSL no tiene ya sentido. @JJ, te hemos enviado un correo desde GranaSAT para eliminar este equipo del concurso.
¡Gracias y perdona las molestias!
